# Generated by Django 2.1.5 on 2019-01-07 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='소식 받을 이메일')),
                ('telegram_id', models.CharField(blank=True, max_length=30, verbose_name='소식 받을 텔레그램')),
                ('my_tags', models.TextField(blank=True, verbose_name='내가 선택한 태그')),
                ('my_jokbo', models.TextField(blank=True, verbose_name='내가 선택한 족보')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
